# Generated by Django 4.0.3 on 2023-03-04 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
