# Generated by Django 4.0.3 on 2023-03-04 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_created_at_post_created_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
