# Generated by Django 4.0.3 on 2023-03-04 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='images',
        ),
    ]
